### ISSUE TITLE
Is the mod died ?

### ISSUE THREAD

**Issue by Fungie2134** [Tschrock/MC-TouchControls#3]
Is the mod died ? Will it be updated to 1.10.2 ?

**Comment by Tschrock** [comment]
I am no longer using the original tablet I made this on, though it's probably still laying around somewhere. I don't have any plans on updating this at the moment, but if anyone else wants to work on it, go ahead! I'll gladly answer any questions about how it works.

**Comment by Fungie2134** [comment]
I would like to update it myself if it is not.
What major change should I do to make it work ( if you do not know I will find, but saving time is a good idea ).

**Comment by Fungie2134** [comment]
I finally decided to update this project, I know a lot of peoples who needs something like that.
