### ISSUE TITLE
Uploaded code incomplete ? Missing some classes...

### ISSUE THREAD

**Issue by Fungie2134** [Tschrock/MC-TouchControls#4]
I finally decided to update this project, I know a lot of peoples who needs something like that.
So, I ran a _git clone_ command, the _gradle setupDecompWorkspace_ followed by _gradle eclipse_.
After I wanted to try it directly, so _gradle runclient_ : Build failed.
Finnaly some classes are missing, like the IMCGuiTouchable one, I tried to get them from the jar, which led me to some errors because of decompiling...
Do you still have the original workspace ? If you do may you fix this issue?
Thanks in advance !

**Comment by Tschrock** [comment]
I'll dig through some old files and see if I can find anything

**Comment by Fungie2134** [comment]
Thanks ! I hope you will
( Maybe there's a copy on the original tablet you made it on? )

**Comment by Fungie2134** [comment]
Did you find anything? ( I hope you have enough time to do so, else, I can wait ).

**Comment by Tschrock** [comment]
Found an older version of the project with some loose files. Hopefully that helps a bit.

**Comment by Aang23** [comment]
Thanks ! This should be enough to get it working
